### ISSUE TITLE
ZeroconfResolver.ResolveAsync not working with avahi-daemon

### ISSUE THREAD

**Issue by pdgmdm** [onovotny/Zeroconf#128]
I am trying to resolve a bonjour service on another device.
I call the ZeroconfResolver.ResolveAsync from my device -- a RPi runningRaspbian --  were I have also registered another bonjour service, so the avahi-daemon is running.
I always get this error:

System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Zeroconf.NetworkInterface.NetworkRequestAsync(Byte[] requestBytes, TimeSpan scanTime, Int32 retries, Int32 retryDelayMilliseconds, Action`2 onResponse, NetworkInterface adapter, CancellationToken cancellationToken) in D:\a\1\s\Zeroconf\NetworkInterface.cs:line 107
   at Zeroconf.NetworkInterface.NetworkRequestAsync(Byte[] requestBytes, TimeSpan scanTime, Int32 retries, Int32 retryDelayMilliseconds, Action`2 onResponse, NetworkInterface adapter, CancellationToken cancellationToken) in D:\a\1\s\Zeroconf\NetworkInterface.cs:line 169
   at Zeroconf.NetworkInterface.NetworkRequestAsync(Byte[] requestBytes, TimeSpan scanTime, Int32 retries, Int32 retryDelayMilliseconds, Action`2 onResponse, CancellationToken cancellationToken) in D:\a\1\s\Zeroconf\NetworkInterface.cs:line 34
   at Zeroconf.ZeroconfResolver.ResolveInternal(ZeroconfOptions options, Action`2 callback, CancellationToken cancellationToken) in D:\a\1\s\Zeroconf\ZeroconfResolver.cs:line 79
   at Zeroconf.ZeroconfResolver.BrowseDomainsAsync(BrowseDomainsOptions options, Action`2 callback, CancellationToken cancellationToken) in D:\a\1\s\Zeroconf\ZeroconfResolver.Async.cs:line 164
   at Zeroconf.ZeroconfResolver.BrowseDomainsAsync(TimeSpan scanTime, Int32 retries, Int32 retryDelayMilliseconds, Action`2 callback, CancellationToken cancellationToken) in D:\a\1\s\Zeroconf\ZeroconfResolver.Async.cs:line 136

Note that when I stop the avahi-daemon, the ResolveAsync is working fine. 
Is there a solution to get the ResolveAsync working, even when the avahi-daemon is running ??

Many thanks.

**Comment by pdgmdm** [comment]
I found that this issue is linked to  https://github.com/richardschneider/net-mdns/issues/22
I can be solved by adding following lines of code just before the binding is done (Networkinterfae.cs line 151):

                if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    LinuxHelper.ReuseAddresss(socket);
                } 

(using dotnet package Tmds.LibC, https://github.com/tmds/Tmds.LibC)

**Comment by onovotny** [comment]
Is this still an issue when running on .NET Core 3? What OS/architecture?

**Comment by pdgmdm** [comment]
.NET Core 3 seems to have fixed this!
