### ISSUE TITLE
Errors on Windows Phone 10 Preview

### ISSUE THREAD

**Issue by mcecile** [onovotny/Zeroconf#14]
I realize that Windows Phone is pre-release software but I thought I would give a heads-up. The problem does not occur on a Lumia 1520 running Windows Phone 8.1.

When running the ZeroconfTest.WP on a Lumia 635 running Windows 10 Preview, I get numerous errors (see below). It seems that these are on a call to BrowseDomainsAsync or ResolveAsync. 

A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
WinRT information: Only one usage of each socket address (protocol/network address/port) is normally permitted.

A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
WinRT information: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Exception trying to Bind:System.Exception: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Only one usage of each socket address (protocol/network address/port) is normally permitted.

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zeroconf.NetworkInterface.<BindToSocketAndWriteQuery>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__4.MoveNext()
Retrying in 2000 ms
A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
WinRT information: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by onovotny** [comment]
Closing for now. Please try the latest versions and re-open if it's still an issue.

Thanks!
