### ISSUE TITLE
Error with Universal Windows apps

### ISSUE THREAD

**Issue by doodz** [onovotny/Zeroconf#17]
when the method BrowseDomainsAsync() is called :

message =>A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)

stackTrace =>    at Windows.Networking.Sockets.DatagramSocket.BindServiceNameAsync(String localServiceName, NetworkAdapter adapter)
   at Zeroconf.NetworkInterface.<BindToSocketAndWriteQuery>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.ZeroconfResolver.<ResolveInternal>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zeroconf.ZeroconfResolver.<BrowseDomainsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CroutonFramework.Utils.EnumerateAllServicesFromAllHosts.<ResolveAsync>d__0.MoveNext()

**Comment by onovotny** [comment]
Closing for now. Please try the latest and re-open if this is still an issue.
