### ISSUE TITLE
ZeroconfResolver.ResolveContinuous causes System.NullReferenceException

### ISSUE THREAD

**Issue by wadenweh** [onovotny/Zeroconf#54]
Hi, I am using the ZeroconfResolver.ResolveContinuous() Method to watch for new camera devices in my local network. Pretty randomly, I am getting a System.NullReferenceException. Am I doing something wrong? I am not very experienced with Rx, it is my first try :) 

The Code is running on a windows 7 machine. The Frameworkversion is 4.61.

My Code:
```csharp       
        public VirbCameraProvider()
        {
            Cameras = new ObservableCollection<Virb>();
            m_Disposables = new List<IDisposable>();
            m_Disposables.Add(ZeroconfResolver.ResolveContinuous("_garmin-virb._tcp.local.")
                .ObserveOn(SynchronizationContext.Current)
                .Subscribe(HostFound));
        }
...
        private void HostFound(IZeroconfHost host)
        {
            if (!host.Services.ContainsKey("_garmin-virb._tcp.local.") || host.Id != host.IPAddress) return;
            if (Cameras.Any(v => v.Ip == host.IPAddress || v.Name == host.DisplayName))
            {
                var ipChangedVirb = Cameras.SingleOrDefault(v => v.Name == host.DisplayName && v.Ip != host.IPAddress);
                if (ipChangedVirb == null)
                    return;
                RemoveCamera(ipChangedVirb);
            }
            var virb = new Virb(host.IPAddress, host.DisplayName);
            virb.StateNull
                .ObserveOn(SynchronizationContext.Current)
                .Subscribe(count =>
            {
                if (count > 4)
                    RemoveCamera(virb);
            });
            Cameras.Add(virb);
        }
```

Stack Trace:
```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 33
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveInternal>d__4.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.cs:line 75
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveAsync>d__15.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.Async.cs:line 69
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<>c__DisplayClass8_0.<<Resolve>b__0>d.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.Observable.cs:line 56
    --- End of stack trace from previous location where exception was thrown ---
       at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exception exception)
       at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
       at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
       at System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnErrorPosted(Object error)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at PavementPicker.App.Main() in C:\dev\euk\PavementPicker\PavementPicker\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by samal84** [comment]
I am getting intermittend NullReferenceExceptions too from ZeroconfResolver.ResolveAsync.

Out workaround is to use System.Timers.Timer to call ZeroconfResolver.ResolveAsync inside a try/catch every 10 seconds. It fails every 20 times or so. But we can live with that.

**Comment by onovotny** [comment]
So not saying there isn't a bug here (we should really never be throwing `NullReferenceExcetions`), but it is possible to have exceptions/errors in reactive sequences that you have to deal with.

I recommend some of the techniques here:
http://www.introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html#AdvancedErrorHandling

**Comment by onovotny** [comment]
I'm having a tough time trying to find the actual place that's throwing this though. Can you please disable `Just My Code` and set a first chance exception break for `NullReferenceException` to get a better call stack?

**Comment by wadenweh** [comment]
okidoke, let me try

**Comment by wadenweh** [comment]
I got one, with Just My Code disabled:
`System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=System
  StackTrace:
       at System.Net.Sockets.UdpClient.EndReceive(IAsyncResult asyncResult, IPEndPoint& remoteEP)
       at System.Net.Sockets.UdpClient.<ReceiveAsync>b__64_1(IAsyncResult ar)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException: 


System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=System
  StackTrace:
       at System.Net.Sockets.UdpClient.EndReceive(IAsyncResult asyncResult, IPEndPoint& remoteEP)
       at System.Net.Sockets.UdpClient.<ReceiveAsync>b__64_1(IAsyncResult ar)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.NetworkInterface.<>c__DisplayClass1_2.<<NetworkRequestAsync>b__1>d.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 124
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException: 


System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 79
  InnerException: 

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
  InnerException: 

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException: 

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 33
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException: 

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 33
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveInternal>d__4.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.cs:line 75
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException: 

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 33
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveInternal>d__4.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.cs:line 75
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveAsync>d__15.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.Async.cs:line 69
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException: 

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Zeroconf
  StackTrace:
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 159
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 33
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveInternal>d__4.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.cs:line 75
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<ResolveAsync>d__15.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.Async.cs:line 69
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Zeroconf.ZeroconfResolver.<>c__DisplayClass8_0.<<Resolve>b__0>d.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.Observable.cs:line 56
    --- End of stack trace from previous location where exception was thrown ---
       at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exception exception)
  InnerException: 
`

**Comment by onovotny** [comment]
Thanks, that's helpful. There's basically a race condition in the Dispose of the UdpClient and the listener thread. The core issue is that we can't cleanly break from the `ReceiveAsync` so we force the dispose. The correct fix here is for the listener loop to swallow that exception. I'll take care of this.

**Comment by onovotny** [comment]
Should be fixed in https://github.com/onovotny/Zeroconf/commit/c5f184d8b76d4e70eb2393a764679020af7b79ca

**Comment by onovotny** [comment]
2.7.2 is live on NuGet with this fix: https://www.nuget.org/packages/Zeroconf/2.7.2

**Comment by wadenweh** [comment]
Thanks!
